#!/usr/bin/env bash
#Script to install and configure HAproxy

#Install HAproxy
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

# Make sure HAproxy can be managed via an init script
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

# Make a backup config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Configure HAproxy so that it sends traffic to web-01 and web-02 & distributes with roundrobin
sudo sed -i "$ a\listen ornellarx \n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 3867-web-01 34.138.104.139:80 check\n\tserver 3867-web-02 54.89.111.28:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start

