#!/usr/bin/env bash
# Bash script that:
#    Creates the file /var/run/myscript.pid containing its PID
#    Displays To infinity and beyond indefinitely
#    Displays I hate the kill command when receiving a SIGTERM signal
#    Displays Y U no love me?! when receiving a SIGINT signal
#    Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

rm_terminate()
{
	rm -f /var/run/myscript.pid;
	exit
}

trap "echo 'I hate the kill command'; rm_terminate" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm_terminate" SIGQUIT

echo $$ >> /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
done

