#!/usr/bin/env bash
# Bash script that displays:
#     To infinity and beyond indefinitely
#     With a sleep 2 in between each iteration
#     I am invincible!!! when receiving a SIGTERM signal

rec_sig()
{
	echo "I am invincible!!!"
}
trap "rec_sig" SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done

