#!/usr/bin/env bash
# Bash script that displays Best School 10 times using a while loop
# and during the 9th iteration displays Best School and then Hi

i=0
while ((i<10)); do
	echo 'Best School'
	if ((i==8)); then
		echo 'Hi'
	fi
	((i++))
done

