#!/usr/bin/env bash
# Bash script that displays:
# 	- content of current directory
#	- in a list format
# 	- only the part of the name after the first dash is displayed

# for file in *;
# do
# 	echo "${file:2}"
# done


for file in *;
do
	for num in {0..9}
	do
		if [ "${file:0:1}" == "$num" ]; then
			echo "${file:2}"
		fi
	done
done

