#!/usr/bin/env bash
# Configure ufw and block all incoming traffic, except the TCP ports 22, 80, 443
sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable

