#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
#    localhost resolves to 127.0.0.2
#    facebook.com resolves to 8.8.8.8.

FACEBOOK="8.8.8.8	facebook.com"

cp /etc/hosts etc_hosts_tmp
sed -i s/127.0.0.1/127.0.0.2/g etc_hosts_tmp
echo "$FACEBOOK" >> etc_hosts_tmp
cp -f hosts_tmp etc_hosts_tmp

