#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
#    localhost resolves to 127.0.0.2
#    facebook.com resolves to 8.8.8.8.

FACEBOOK="8.8.8.8	facebook.com"

cp /etc/hosts ~/hosts.new
sed -i "s/.*localhost/127.0.0.2 localhost/g" ~/hosts.new
echo "$FACEBOOK" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts

