#!/usr/bin/env bash
# Script to connect to your server using the private key ~/.ssh/school with the user ubuntu
# Requirements:
 # Only use ssh single-character flags
 # You cannot use -l

ssh -i ~/.ssh/school ubuntu@34.138.104.139
